### ISSUE TITLE
dictionary changed size during iteration

### ISSUE THREAD

**Issue by guicercal** [diracdeltas/spleeter4max#11]
**Describe the issue**
Im trying to run spleeter-native (wich uses an existing spleeter instalation, without docker) on macos catalina terminal, and im facing this issue:

Traceback (most recent call last):
  File "/usr/local/bin/spleeter", line 10, in <module>
    sys.exit(entrypoint())
  File "/Library/Python/3.7/site-packages/spleeter/__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "/Library/Python/3.7/site-packages/spleeter/__main__.py", line 36, in main
    enable_logging()
  File "/Library/Python/3.7/site-packages/spleeter/utils/logging.py", line 60, in enable_logging
    tf_logger = get_tensorflow_logger()
  File "/Library/Python/3.7/site-packages/spleeter/utils/logging.py", line 27, in get_tensorflow_logger
    from tensorflow.compat.v1 import logging
  File "/Library/Python/3.7/site-packages/tensorflow/__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "/Library/Python/3.7/site-packages/tensorflow_core/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "<frozen importlib._bootstrap>", line 1019, in _handle_fromlist
  File "/Library/Python/3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/Library/Python/3.7/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Library/Python/3.7/site-packages/tensorflow_core/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Library/Python/3.7/site-packages/tensorflow_core/core/framework/graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Library/Python/3.7/site-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/Library/Python/3.7/site-packages/pkg_resources/__init__.py", line 84, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/Library/Python/3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Library/Python/3.7/site-packages/pkg_resources/extern/__init__.py", line 43, in load_module
    __import__(extant)
  File "/Library/Python/3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 4756, in <module>
    _escapedPunc = Word( _bslash, r"\[]-*.$+^?()~ ", exact=2 ).setParseAction(lambda s,l,t:t[0][1])
  File "/Library/Python/3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1284, in setParseAction
    self.parseAction = list(map(_trim_arity, list(fns)))
  File "/Library/Python/3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1066, in _trim_arity
    this_line = extract_stack(limit=2)[-1]
  File "/Library/Python/3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1050, in extract_stack
    frame_summary = traceback.extract_stack(limit=-offset+limit-1)[offset]
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 363, in extract
    f.line
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 285, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 48, in getlines
    for mod in sys.modules.values():
RuntimeError: dictionary changed size during iteration

i tried to run in Ableton live using max before but without success. it gives me:

![image](https://user-images.githubusercontent.com/7075482/82132679-a79bbe80-97b8-11ea-8a97-bec9c878493e.png)

**Comment by diracdeltas** [comment]
does the same error appear if you enter the `spleeter separate -i ...` command in terminal?

**Comment by diracdeltas** [comment]
also is this python 3.7 installed from Homebrew (https://docs.python-guide.org/starting/install3/osx/) or something else?

**Comment by guicercal** [comment]
> does the same error appear if you enter the `spleeter separate -i ...` command in terminal?

yes, actually i tried to run inside the ableton and after i tried to run on the terminal, with and without sudo

**Comment by guicercal** [comment]
> also is this python 3.7 installed from Homebrew (https://docs.python-guide.org/starting/install3/osx/) or something else?

yes, my python version is 3.7.3, and i previously installed it from homebrew few months ago for other reasons..

**Comment by diracdeltas** [comment]
> yes, my python version is 3.7.3, and i previously installed it from homebrew few months ago for other reasons..

i would try doing a brew update to 3.7.7 just to see if that makes a difference

**Comment by diracdeltas** [comment]
seems likely this is an upstream tensorflow issue https://github.com/tensorflow/tensorflow/issues/33183

it may have been fixed in tensorflow 1.15 but i think spleeter (the deezer library) requires an earlier version :(

**Comment by diracdeltas** [comment]
this comment suggests updating to python 3.7.5 fixes it: https://github.com/tensorflow/tensorflow/issues/33183#issuecomment-557915426
