### ISSUE TITLE
"Error: Command Failed" due to missing DLL - Spleeter-Native for Windows 10

### ISSUE THREAD

**Issue by gfhsrtras** [diracdeltas/spleeter4max#27]
After I have selected the clip and pressed start, the program buffers for a bit. It says it's running but then stops and comes up with an error message saying "Error: Command Failed" then a bunch of script after that listing out filenames etc. 

I've opened it up in the max console and it says this:
node.script: Loaded the spleeter.js script

comment: doesn't understand "bang"

node.script: spleeter separate -i "C:/spleeter-native/test.wav" -o "C:\spleeter-native" -p spleeter:4stems-16kHz

js: js: no function set [main.js]

js: js: no function set [main.js]

"node.script: Error: Command failed: spleeter separate -i "C:/spleeter-native/test.wav" -o "C:\spleeter-native" -p spleeter:4stems-16kHz
Traceback (most recent call last):
  File "c:\users\hugow\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\hugow\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\hugow\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\hugow\appdata\local\programs\python\python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\hugow\appdata\local\programs\python\python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hugow\AppData\Local\Programs\Python\Python37\Scripts\spleeter-script.py", line 11, in <module>
    load_entry_point('spleeter==1.5.2', 'console_scripts', 'spleeter')()
  File "c:\users\hugow\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\hugow\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 36, in main
    enable_logging()
  File "c:\users\hugow\appdata\local\programs\python\python37\lib\site-packages\spleeter\utils\logging.py", line 60, in enable_logging
    tf_logger = get_tensorflow_logger()
  File "c:\users\hugow\appdata\local\programs\python\python37\lib\site-packages\sp

node.script: Spleeter stderr: Traceback (most recent call last):
  File "c:\users\hugow\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\hugow\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\hugow\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\hugow\appdata\local\programs\python\python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\hugow\appdata\local\programs\python\python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hugow\AppData\Local\Programs\Python\Python37\Scripts\spleeter-script.py", line 11, in <module>
    load_entry_point('spleeter==1.5.2', 'console_scripts', 'spleeter')()
  File "c:\users\hugow\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\hugow\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 36, in main
    enable_logging()
  File "c:\users\hugow\appdata\local\programs\python\python37\lib\site-packages\spleeter\utils\logging.py", line 60, in enable_logging
    tf_logger = get_tensorflow_logger()
  File "c:\users\hugow\appdata\local\programs\python\python37\lib\site-packages\spleeter\utils\logging.py", line 27, in get_tensorflow_logger
    from tensorflow.compat.v1 import logging

node.script: Spleeter stdout: 

comment: doesn't understand "spleeterDone"

**Comment by diracdeltas** [comment]
looks like you're missing a DLL. if you follow all the steps in https://github.com/diracdeltas/spleeter4max/tree/feature/native-spleeter#windows-steps and then run the check-install.py command at the end, does it say anything failed?

**Comment by gfhsrtras** [comment]
after check-install it says "python: can't open file 'check-install.py': [Errno 2] No such file or directory"

also after I type ffmpeg it says "'ffmpg' is not recognized as an internal or external comman, operable program or batch file."

**Comment by diracdeltas** [comment]
> after check-install it says "python: can't open file 'check-install.py': [Errno 2] No such file or directory"

you have to run the script in the directory where you downloaded the check-install.py file

> also after I type ffmpeg it says "'ffmpg' is not recognized as an internal or external comman, operable program or batch file."

so it appears the issue is ffmpeg wasn't actually installed correctly. did you do step 4 of https://github.com/adaptlearning/adapt_authoring/wiki/Installing-FFmpeg?

**Comment by gfhsrtras** [comment]
Sorry i'm not sure what you mean when you say "run the script in the directory where you downloaded the check-install.py file". I'm a bit technologically retarded so I might need to you spell it out for me.

After step 4 of the ffmpeg instructions it says "SUCCESS: Specified value was saved." but still the same outcome after typing ffmpeg.

**Comment by diracdeltas** [comment]
> Sorry i'm not sure what you mean when you say "run the script in the directory where you downloaded the check-install.py file". I'm a bit technologically retarded so I might need to you spell it out for me.

no worries, i think it's not necessary to run this anymore given that we have identified the problem is probably ffmpeg. if you open CMD.exe and type `where ffmpeg`, what does it show?

**Comment by diracdeltas** [comment]
and also try typing `echo %PATH%` in CMD.exe to make sure wherever ffmpeg was installed is actually in your path

**Comment by gfhsrtras** [comment]
After ffmpeg: 
"'ffmpeg' is not recognized as an internal or external comman, operable program or batch file."

After echo %PATH%: "path\to\ffmpeg\bin;path\to\ffmpeg\bin;C:\Users\hugow\AppData\Local\Microsoft\WindowsApps;C:\ffmpeg;C:\Users\hugow\AppData\Local\Microsoft\WindowsApps;C:\Users\hugow\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\hugow\AppData\Local\Programs\Python\Python37";C:\Users\hugow\AppData\Local\Programs\Python\Python37\"

**Comment by diracdeltas** [comment]
@gfhsrtras ah, i see the problem. instead of inserting literally `path\to\ffmpeg\bin` in the PATH, you have to find where FFMPEG was downloaded to and *insert the path to that* in the PATH variable. for instance `C:\Users\hugow\ffmpeg\bin` if you downloaded it to your home folder.

see the last sentence of https://github.com/adaptlearning/adapt_authoring/wiki/Installing-FFmpeg step 4

**Comment by diracdeltas** [comment]
if you're having trouble figuring out the correct path feel free to ask for help in my discord: https://discord.gg/Y6wH5k
