### ISSUE TITLE
macosx 10.11 native spleeter 

### ISSUE THREAD

**Issue by mastoppa** [diracdeltas/spleeter4max#35]
**Hello i am trying to use native version on macbook 0sx 10.11 el capitan
sorry "non technical user" here i wish i could use the docked version but i own an old macbook and do not want to upgrade osx now...
python default version 2.7.10
python 3 version 3.7.7
ableton 10.1 max 8.1
max error log:**
__node.script: Spleeter stderr: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
  Referenced from: /usr/local/lib/python3.7/site-packages/tensorflow_core/python/../libtensorflow_framework.1.dylib
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /usr/local/lib/python3.7/site-packages/tensorflow_core/python/../libtensorflow_framework.1.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/spleeter", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.7/site-packages/spleeter/__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/spleeter/__main__.py", line 36, in main
    enable_logging()
  File "/usr/local/lib/python3.7/site-packages/spleeter/utils/logging.py", line 60, in enable_logging
    tf_logger = get_tensorflow_logger()
  File "/usr/local/lib/python3.7/site-packages/spleeter/utils/logging.py", line__ 

**IF i run the check-install.py there is an error too!!:**

Checking install...
Traceback (most recent call last):
  File "/Users/matteo/check-install.py", line 17, in <module>
    ffmpeg_result = subprocess.run(['ffmpeg'], capture_output=True).stderr.decode('utf-8')
  File "/usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
>>> 

**THANKS**

**Comment by diracdeltas** [comment]
did you make sure to install ffmpeg with `brew install ffmpeg` before running? (see instructions)

**Comment by diracdeltas** [comment]
actually i just looked at your actual error and it appears to be this: https://github.com/tensorflow/tensorflow/issues/24642

unfortunately i think this means your MacOS is too old to run tensorflow (see #9), which spleeter requires :(.

**Comment by mastoppa** [comment]
oh thanks, any workaround to install maybe a older version of tensorflow...?

**Comment by diracdeltas** [comment]
unfortunately spleeter currently requires that version of tensorflow, so while it may be possible, it could be a lot of work. see suggestions in https://github.com/diracdeltas/spleeter4max/issues/33. going to close this since it's the same as that issue.

the docker version might work here. also the vst3 could be an option.
