### ISSUE TITLE
Error in Ableton

### ISSUE THREAD

**Issue by FonzSolo** [diracdeltas/spleeter4max#38]
**Did you read the installation instructions already?  Yes
If not, read them BEFORE opening an issue. Go to https://github.com/diracdeltas/spleeter4max#before-you-start (spleeter) or https://github.com/diracdeltas/spleeter4max/blob/feature/native-spleeter/README.md#before-you-start (spleeter-native).

**Describe the issue**
After Pressing Start, It looks like spleeter is going to run and then I get an error message on the device itself.
![Error](https://user-images.githubusercontent.com/66977712/84842159-6cd4b280-b012-11ea-85de-e04806fba4e8.jpg)

**Max Console Screenshots**
Add max console screenshots to help explain your problem. See here for instructions: https://github.com/diracdeltas/spleeter4max#help-its-still-not-working

**Info:**
 - Using spleeter or spleeter-native?
 - OS: [Windows 10 Home 1909]
 - Ableton version [e.g. 10.1.14]
 - Max version [e.g. 8.1.4]

**Comment by diracdeltas** [comment]
can you post a screenshot of the max console as mentioned in https://github.com/diracdeltas/spleeter4max#help-its-still-not-working?

**Comment by federico-pepe** [comment]
I got the same error: here's the Max's console output

```
node.script: Loaded the spleeter.js script
comment: doesn't understand "bang"
node.script: spleeter separate -i "/Users/aloudcollege/Desktop/Prendila così-m_VIMUP2RoY.mp3" -o "/Users/Shared/Ableton/User Library/Max for Live/spleeter-native" -p spleeter:4stems-16kHz
js: js: no function set [main.js]
js: js: no function set [main.js]
node.script: Error: Command failed: spleeter separate -i "/Users/aloudcollege/Desktop/Prendila così-m_VIMUP2RoY.mp3" -o "/Users/Shared/Ableton/User Library/Max for Live/spleeter-native" -p spleeter:4stems-16kHz
Traceback (most recent call last):
  File "/usr/local/bin/spleeter", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.7/site-packages/spleeter/__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/spleeter/__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "/usr/local/lib/python3.7/site-packages/spleeter/commands/separate.py", line 45, in entrypoint
    synchronous=False
  File "/usr/local/lib/python3.7/site-packages/spleeter/separator.py", line 231, in separate_to_file
    bitrate, synchronous)
  File "/usr/local/lib/python3.7/site-packages/spleeter/separator.py", line 268, in save_to_file
    os.makedirs(directory)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/Shared/Ableton/User Library/Max for Live/spleeter-native/Prendila così-m_VIMUP2RoY'
node.script: Spleeter stderr: Traceback (most recent call last):
  File "/usr/local/bin/spleeter", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.7/site-packages/spleeter/__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/spleeter/__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "/usr/local/lib/python3.7/site-packages/spleeter/commands/separate.py", line 45, in entrypoint
    synchronous=False
  File "/usr/local/lib/python3.7/site-packages/spleeter/separator.py", line 231, in separate_to_file
    bitrate, synchronous)
  File "/usr/local/lib/python3.7/site-packages/spleeter/separator.py", line 268, in save_to_file
    os.makedirs(directory)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/Shared/Ableton/User Library/Max for Live/spleeter-native/Prendila così-m_VIMUP2RoY'
node.script: Spleeter stdout: 
comment: doesn't understand "spleeterDone"
```

But I solved it by updating the Folder's **Sharing and Permissions** preferences: just select the folder, hit `cmd+i` and check that the current user has Read/Write permission

**Comment by FonzSolo** [comment]
node.script: Loaded the spleeter.js script
comment: doesn't understand "bang"
node.script: spleeter separate -i "I:/Ableton/Live Recordings/My_Projects/Muzik/Curtis Mayfield Project/Samples/Processed/Consolidate/Tripping Out 1 [2020-06-18 193550].wav" -o "C:\Users\asmed\Desktop\Spleeter\spleeter-native" -p spleeter:4stems-16kHz
js: js: no function set [main.js]
node.script: Error: Command failed: spleeter separate -i "I:/Ableton/Live Recordings/My_Projects/Muzik/Curtis Mayfield Project/Samples/Processed/Consolidate/Tripping Out 1 [2020-06-18 193550].wav" -o "C:\Users\asmed\Desktop\Spleeter\spleeter-native" -p spleeter:4stems-16kHz
node.script: Spleeter stderr: 
node.script: Spleeter stdout: 
comment: doesn't understand "spleeterDone"
js: js: no function set [main.js]


> can you post a screenshot of the max console as mentioned in https://github.com/diracdeltas/spleeter4max#help-its-still-not-working?

**Comment by diracdeltas** [comment]
closing this in favor of https://github.com/diracdeltas/spleeter4max/issues/41
