### ISSUE TITLE
Spleeter works in cmd, Spleeter4Max throws error

### ISSUE THREAD

**Issue by hemenge133** [diracdeltas/spleeter4max#42]
Here's the m4l output

>`Error: Command failed: spleeter separate -i "C:/Users/H/Desktop/Youtube Rips/play date.mp3" -o "C:\Program Files\Spleeter\spleeter-native" -p spleeter:4stems-16kHz
Traceback (most recent call last):
  File "C:\Users\H\AppData\Local\Programs\Python\Python37\Scripts\spleeter-script.py", line 11, in <module>
    load_entry_point('spleeter==1.5.3', 'console_scripts', 'spleeter')()
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 36, in main
    enable_logging()
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\spleeter\utils\logging.py", line 60, in enable_logging
    tf_logger = get_tensorflow_logger()
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\spleeter\utils\logging.py", line 27, in get_tensorflow_logger
    from tensorflow.compat.v1 import logging
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "<frozen importlib._bootstrap>", line 1019, in _handle_fromlist
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "c:\users\h\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\__init__.py", line 83, in <module>
    from tensorflow.python import keras
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\keras\__init__.py", line 26, in <module>
    from tensorflow.python.keras import activations
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\keras\__init__.py", line 26, in <module>
    from tensorflow.python.keras import activations
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\keras\activations.py", line 23, in <module>
    from tensorflow.python.keras.utils.generic_utils import deserialize_keras_object
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\keras\utils\__init__.py", line 38, in <module>
    from tensorflow.python.keras.utils.multi_gpu_utils import multi_gpu_model
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\keras\utils\multi_gpu_utils.py", line 22, in <module>
    from tensorflow.python.keras.engine.training import Model
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 47, in <module>
    from tensorflow.python.keras.engine import training_arrays
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 41, in <module>
    from scipy.sparse import issparse  # pylint: disable=g-import-not-at-top
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\scipy\__init__.py", line 104, in <module>
    from . import _distributor_init
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\scipy\_distributor_init.py", line 61, in <module>
    WinDLL(os.path.abspath(filename))
  File "c:\users\h\appdata\local\programs\python\python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 1`

And the m4l console output

>`node.script: Loaded the spleeter.js script
node.script: spleeter separate -i "C:/Users/H/Desktop/Youtube Rips/play date.mp3" -o "C:\Program Files\Spleeter\spleeter-native" -p spleeter:4stems-16kHz
node.script: Error: Command failed: spleeter separate -i "C:/Users/H/Desktop/Youtube Rips/play date.mp3" -o "C:\Program Files\Spleeter\spleeter-native" -p spleeter:4stems-16kHz
Traceback (most recent call last):
  File "C:\Users\H\AppData\Local\Programs\Python\Python37\Scripts\spleeter-script.py", line 11, in <module>
    load_entry_point('spleeter==1.5.3', 'console_scripts', 'spleeter')()
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 36, in main
    enable_logging()
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\spleeter\utils\logging.py", line 60, in enable_logging
    tf_logger = get_tensorflow_logger()
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\spleeter\utils\logging.py", line 27, in get_tensorflow_logger
    from tensorflow.compat.v1 import logging
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "<frozen importlib._bootstrap>", line 1019, in _handle_fromlist
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "c:\users\h\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-package
node.script: Spleeter stderr: Traceback (most recent call last):
  File "C:\Users\H\AppData\Local\Programs\Python\Python37\Scripts\spleeter-script.py", line 11, in <module>
    load_entry_point('spleeter==1.5.3', 'console_scripts', 'spleeter')()
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 36, in main
    enable_logging()
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\spleeter\utils\logging.py", line 60, in enable_logging
    tf_logger = get_tensorflow_logger()
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\spleeter\utils\logging.py", line 27, in get_tensorflow_logger
    from tensorflow.compat.v1 import logging
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "<frozen importlib._bootstrap>", line 1019, in _handle_fromlist
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "c:\users\h\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\__init__.py", line 83, in <module>
    from tensorflow.python import keras
  File "c:\users\h\appdata\local\programs\pyt
node.script: Spleeter stdout: 
`

Again, I've successfully seperated a track in the command line, so spleeter is not the problem.

**Comment by diracdeltas** [comment]
> Again, I've successfully seperated a track in the command line, so spleeter is not the problem.

i assume this is just using `spleeter separate -i`? can you check `where spleeter` in command line and post the result?

**Comment by diracdeltas** [comment]
spleeter4max just calls out to the command line, so if you want to try a different command and see if it works, you can edit this line in the spleeter.js file (should be in the same folder as the spleeter device): https://github.com/diracdeltas/spleeter4max/blob/feature/native-spleeter/spleeter.js#L42

**Comment by hemenge133** [comment]
@diracdeltas  spleeter is in:
AppData\Local\Programs\Python\Python37\Scripts\spleeter.exe
Could spleeter possibly need elevation for certain folders?

**Comment by diracdeltas** [comment]
it might need to run as admin for some folders. see https://github.com/diracdeltas/spleeter4max/issues/7

**Comment by hemenge133** [comment]
Works. Thank you! I thought my issue was different from #7 because of the error code.
