### ISSUE TITLE
same issue as #41 exactly but i dont see how to fix the issue

### ISSUE THREAD

**Issue by maltese454** [diracdeltas/spleeter4max#51]
**Did you read the installation instructions already?** 
If not, read them BEFORE opening an issue. Go to https://github.com/diracdeltas/spleeter4max#before-you-start (spleeter) or https://github.com/diracdeltas/spleeter4max/blob/feature/native-spleeter/README.md#before-you-start (spleeter-native).

**Describe the issue**
A clear description of what problem you are having.

**Max Console Screenshots**
Add max console screenshots to help explain your problem. See here for instructions: https://github.com/diracdeltas/spleeter4max#help-its-still-not-working

**Info:**
 - Using spleeter or spleeter-native?
 - OS: [e.g. Windows]
 - Ableton version [e.g. 10.1.9]
 - Max version [e.g. 8.1.2]

**Comment by maltese454** [comment]
> **Did you read the installation instructions already?**
> If not, read them BEFORE opening an issue. Go to https://github.com/diracdeltas/spleeter4max#before-you-start (spleeter) or https://github.com/diracdeltas/spleeter4max/blob/feature/native-spleeter/README.md#before-you-start (spleeter-native).
> 
> **Describe the issue**
> A clear description of what problem you are having.
> 
> **Max Console Screenshots**
> Add max console screenshots to help explain your problem. See here for instructions: https://github.com/diracdeltas/spleeter4max#help-its-still-not-working
> 
> **Info:**
> 
> * Using spleeter or spleeter-native?
> * OS: [e.g. Windows]
> * Ableton version [e.g. 10.1.9]
> * Max version [e.g. 8.1.2]
node.script: Loaded the spleeter.js script
node.script: spleeter separate -i "C:/Users/blake/Desktop/bassline musicv50.wav" -o "C:\Users\blake\Desktop\spleeter-native" -p spleeter:4stems-16kHz
node.script: Error: Command failed: spleeter separate -i "C:/Users/blake/Desktop/bassline musicv50.wav" -o "C:\Users\blake\Desktop\spleeter-native" -p spleeter:4stems-16kHz
Traceback (most recent call last):
  File "c:\users\blake\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "c:\users\blake\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\users\blake\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.19.4 (c:\users\blake\appdata\local\programs\python\python37\lib\site-packages), Requirement.parse('numpy<1.19.0,>=1.16.0'), {'tensorflow'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\blake\AppData\Local\Programs\Python\Python37\Scripts\spleeter-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\users\blake\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 3250, in <module>
    @_call_aside
  File "c:\users\blake\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "c:\users\blake\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\users\blake\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\users\blake\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 598, in _build_from_requi
node.script: Spleeter stderr: Traceback (most recent call last):
  File "c:\users\blake\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "c:\users\blake\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\users\blake\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.19.4 (c:\users\blake\appdata\local\programs\python\python37\lib\site-packages), Requirement.parse('numpy<1.19.0,>=1.16.0'), {'tensorflow'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\blake\AppData\Local\Programs\Python\Python37\Scripts\spleeter-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\users\blake\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 3250, in <module>
    @_call_aside
  File "c:\users\blake\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "c:\users\blake\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\users\blake\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\users\blake\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "c:\users\blake\appdata\local\programs\python\python37\lib\site-packages\pkg_resou
node.script: Spleeter stdout:

**Comment by maltese454** [comment]
also wanna say even though i cant get it to work i had so much fun setting it up

**Comment by diracdeltas** [comment]
hi! try the instructions in
https://github.com/tensorflow/models/issues/9200#issuecomment-687538656 to
downgrade numpy to a supported version

**Comment by maltese454** [comment]
just downgraded sadly did not work but got screenshots
![Capture1](https://user-images.githubusercontent.com/74512194/99223965-5043ce80-279a-11eb-9eb6-461c2060a53c.PNG)
![Capture2](https://user-images.githubusercontent.com/74512194/99223974-52a62880-279a-11eb-8ce1-0e95d242db62.PNG)
![Capture3](https://user-images.githubusercontent.com/74512194/99223983-546fec00-279a-11eb-9527-baf9fcc22828.PNG)

**Comment by maltese454** [comment]
oh my god its working holy shit i had to reinstall a older version of scipy thankyou so much for making this its going to change the way i analyze songs forever

**Comment by diracdeltas** [comment]
yay!
