### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Ariloum** [diracdeltas/spleeter4max#57]
I've installed everything by manuals, check-install.py doesn't returns any errors, 
but when I ran spleeter in console it results this: 
ImportError: Could not find the DLL(s) 'msvcp140.dll or msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads

I've installed already VC++ redists and its in every possible paths already.
What's wrong with this?

Stack trace:
```
$> spleeter separate -o "C:\spleeter-native" -p spleeter:4stems-16kHz "g:\mp3\DUB\1\test.wav"

Traceback (most recent call last):                                                                                            
  File "c:\users\ariloum\anaconda3\lib\runpy.py", line 194, in _run_module_as_main                                            
    return _run_code(code, main_globals, None,                                                                                
  File "c:\users\ariloum\anaconda3\lib\runpy.py", line 87, in _run_code                                                       
    exec(code, run_globals)                                                                                                   
  File "C:\Users\Ariloum\Anaconda3\Scripts\spleeter.exe\__main__.py", line 7, in <module>                                     
  File "c:\users\ariloum\anaconda3\lib\site-packages\spleeter\__main__.py", line 250, in entrypoint                           
    spleeter()                                                                                                                
  File "c:\users\ariloum\anaconda3\lib\site-packages\typer\main.py", line 214, in __call__                                    
    return get_command(self)(*args, **kwargs)                                                                                 
  File "c:\users\ariloum\anaconda3\lib\site-packages\click\core.py", line 829, in __call__                                    
    return self.main(*args, **kwargs)                                                                                         
  File "c:\users\ariloum\anaconda3\lib\site-packages\click\core.py", line 782, in main                                        
    rv = self.invoke(ctx)                                                                                                     
  File "c:\users\ariloum\anaconda3\lib\site-packages\click\core.py", line 1259, in invoke                                     
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                   
  File "c:\users\ariloum\anaconda3\lib\site-packages\click\core.py", line 1066, in invoke                                     
    return ctx.invoke(self.callback, **ctx.params)                                                                            
  File "c:\users\ariloum\anaconda3\lib\site-packages\click\core.py", line 610, in invoke                                      
    return callback(*args, **kwargs)                                                                                          
  File "c:\users\ariloum\anaconda3\lib\site-packages\typer\main.py", line 497, in wrapper                                     
    return callback(**use_params)  # type: ignore                                                                             
  File "c:\users\ariloum\anaconda3\lib\site-packages\spleeter\__main__.py", line 107, in separate                             
    from .audio.adapter import AudioAdapter                                                                                   
  File "c:\users\ariloum\anaconda3\lib\site-packages\spleeter\audio\adapter.py", line 14, in <module>                         
    import tensorflow as tf                                                                                                   
  File "c:\users\ariloum\anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>                            
    from tensorflow.python.tools import module_util as _module_util                                                           
  File "c:\users\ariloum\anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>                     
    from tensorflow.python.eager import context                                                                               
  File "c:\users\ariloum\anaconda3\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>                
    from tensorflow.python import pywrap_tfe                                                                                  
  File "c:\users\ariloum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>                   
    from tensorflow.python import pywrap_tensorflow                                                                           
  File "c:\users\ariloum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>            
    self_check.preload_check()                                                                                                
  File "c:\users\ariloum\anaconda3\lib\site-packages\tensorflow\python\platform\self_check.py", line 54, in preload_check     
    raise ImportError(                                                                                                        
ImportError: Could not find the DLL(s) 'msvcp140.dll or msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a
 directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistr
ibutable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads         
```                                                                                

**Info:**
 - Using spleeter-native?
 - OS: Windows 10
 - Ableton version 11
 - Max version [e.g. 8.1.2]

**Comment by diracdeltas** [comment]
Seems to be a common tensorflow error. Have you tried https://stackoverflow.com/questions/60157335/cant-pip-install-tensorflow-msvcp140-1-dll-missing or https://stackoverflow.com/questions/50777013/tensorflow-importerror-could-not-find-msvcp140-dll/50777261 ?

**Comment by Ariloum** [comment]
I figured it out, it was because my PATH contains python 3.8+, I changed path to 3.7.7 and that error is gone, but now I got another error (file attached). 
[spleeter-error.txt](https://github.com/diracdeltas/spleeter4max/files/6916391/spleeter-error.txt)

**Comment by diracdeltas** [comment]
are you using a GPU? it looks like this issue which has so far only been encountered on GPUs: https://github.com/deezer/spleeter/issues/316#issuecomment-712013108. i'd recommend leaving a comment there since it's an issue with the spleeter command line tool.

**Comment by Ariloum** [comment]
how do I know what I'm using - gpu/cpu? 
I just run it with this console command:
spleeter separate -o "C:\spleeter-native" -p spleeter:4stems-16kHz "g:\mp3\DUB\1\test.wav"

**Comment by diracdeltas** [comment]
probably CPU then. i'd recommend filing an issue in https://github.com/deezer/spleeter/issues

**Comment by Ariloum** [comment]
how can I check what exactly it tries to use? I don't see any load on my CPU or GPU with this spleeter launching at all. It just stuck for half hour or a hour and then drops that error.
I got "stronk" pc(Ryzen 3950x & 3080 gpu & 64gb mem) and also used TF with GPU on java with no issues before. seems like some python issue to me.
